project:
  type: website
  output-dir: docs
  render: 
    - schools_wk2.qmd
    - schools_wk3.qmd
    - stain_removal.qmd
    - factsheet.qmd
    - data_processing_scripts.qmd
    - geocode_planning.qmd

website:
  title: "Brighton and Hove Secondary Schools Admission - Evidence Pages"
  navbar:
    background: primary
    search: true
    left:
      - text: "Data Processing"
        href: data_processing_scripts.qmd
      - about.qmd
      - text: "Week 2 Analysis"
        href: schools_wk2.qmd
      - text: "Week 3 Analysis"
        href: schools_wk3.qmd
      - text: "Addendum"
        href: stain_removal.qmd
      - text: "Factsheet"
        href: factsheet.qmd
    right:
      - icon: person-circle
        href: https://adamdennett.co.uk
      - icon: twitter
        href: https://twitter.com/adam_dennett
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/adamdennett/BH_Schools_2
          - text: Report a Bug
            url:  https://github.com/adamdennett/BH_Schools_2/issues
  repo-url: https://github.com/adamdennett/BH_Schools_2
  repo-actions: [source, issue]
  google-analytics: "G-HFKH18TWMG"
  open-graph: true
  twitter-card: true
   

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true

editor: visual