---
title: "Additional Spatial Analysis"
author: "Adam Dennett"
---


```{r}

#get some LSOA pop weighted centroids for E&W from ONS
url <- "https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/LLSOA_Dec_2021_PWC_for_England_and_Wales_2022/FeatureServer/0/query?outFields=*&where=1%3D1&f=geojson"

# Read the GeoJSON file into an sf object
sf_point_data <- st_read(url)
#save locally
st_write(sf_point_data, here("data", "EW_LSOA_PW_Centoid.geojson"), append = TRUE)

#brighton school data
brighton_school_children <- read_csv(here("data", "BrightonLSOASchoolChildren.csv"))

btn_lsoa_list <- as.data.frame(brighton_school_children$lsoa_code) %>% 
  clean_names()

lsoa_btn_pw_centroids <- sf_point_data %>% 
  st_transform(27700) %>% 
  clean_names %>% 
  select(lsoa21cd, geometry)

lsoa_btn_pw_centroids <- lsoa_btn_pw_centroids %>% right_join(btn_lsoa_list, by = c("lsoa21cd" = "brighton_school_children_lsoa_code"))

st_write(lsoa_btn_pw_centroids, here("data", "lsoa_btn_pw_centroids.geojson"), append = TRUE)
```

```{r, echo=F, message=F, warning=F}

#catchments
bh_catchments <- st_read(here("data","BrightonSecondaryCatchments.geojson"))

#lsoa data
sf_data <- st_read(here("data","EW_LSOA.geojson"))
sf_data <- clean_names(sf_data)

#lsoa data
brighton_lsoa <- sf_data %>% right_join(brighton_school_children, by = c("lsoa21cd" = "lsoa_code"))

#lsoa centroids
brighton_lsoa_centroids <- st_centroid(brighton_lsoa) %>% 
  st_transform(27700)

brighton_lsoa_centroids_simple <- st_centroid(brighton_lsoa) %>% 
  st_transform(27700) %>% 
  select(lsoa21cd, geometry)

brighton_oa <- st_read(here("data","oa_brighton.geojson"))

brighton_roads <- st_read(here("data","brighton_roads.shp"))

#Fix the school and school data so r5 can handle it
#schools first

brighton_sec_schools_wgs84 <- brighton_sec_schools %>%
  st_transform(4326) %>% 
  st_set_crs(4326)

bh_sec_sch <- brighton_sec_schools_wgs84 %>% 
  select(urn, establishment_name, geometry) %>%
  rename(id = urn)

coords <- st_coordinates(bh_sec_sch)
bh_sec_sch$lon <- coords[, 1]
bh_sec_sch$lat <- coords[, 2]

bh_sec_sch_bng <- bh_sec_sch %>% 
  st_transform(27700)

#now the LSOAs
brighton_lsoa_points_r5 <- brighton_lsoa_centroids %>% 
  select(fid, lsoa21cd,lat, long) %>% 
  rename(lon = long, lat = lat, id = fid) %>% 
  st_transform(4326) %>% 
  st_set_crs(4326)

```

```{r, warning=FALSE, message=FALSE, echo=FALSE}
data_path = here("data")
# Check what files we have
#list.files(data_path)

# Allow 10 GiB of memory
rJava::.jinit()
rJava::.jcall("java.lang.System", "S", "getProperty", "java.version")
options(java.parameters = "-Xmx10G")

library(r5r)
library(accessibility)
library(sf)
library(data.table)
library(ggplot2)
library(interp)
library(h3jsr)
library(h3r)
library(dplyr)
library(osmextract)
library(stplanr)

r5r_core = setup_r5(data_path = data_path)

```

```{r}
#travel time matrix

# Set parameters
mode = c("WALK")
max_walk_time = 90 # minutes
max_trip_duration = 90 # minutes
departure_datetime = as.POSIXct("23-05-2024 8:30:00",
                                 format = "%d-%m-%Y %H:%M:%S", 
                                tz = "GMT")

#note the code below already requires the h3 core matrix to be set up

# Calculate the travel time matrix by Transit
ttm_btn_lsoa_to_School = travel_time_matrix(r5r_core = r5r_core,
                          origins = bh_sec_sch,
                          destinations = brighton_lsoa_points_r5,
                          mode = mode,
                          departure_datetime = departure_datetime,
                          max_walk_time = max_walk_time,
                          max_trip_duration = max_trip_duration)

#join codes back to the matrix and get it ready from plotting
ttm_btn_lsoa_to_School$orig_lsoa <- brighton_lsoa_centroids$lsoa21cd[match(ttm_btn_lsoa_to_School$to_id, brighton_lsoa_centroids$fid)]

ttm_btn_lsoa_to_School$dest_sch <- brighton_sec_schools_wgs84$establishment_name[match(ttm_btn_lsoa_to_School$from_id, brighton_sec_schools_wgs84$urn)]

ttm_btn_lsoa_to_School <- ttm_btn_lsoa_to_School %>%
  mutate(to_id = as.factor(to_id)) %>%
  unite(od_code, orig_lsoa, to_id, sep = "_", remove = FALSE)

simple_ttm <- ttm_btn_lsoa_to_School %>%
  select(orig_lsoa, to_id, travel_time_p50) %>% 
  rename(orig = orig_lsoa, dest = to_id, flow = travel_time_p50)

class(ttm_btn_lsoa_to_School)

simple_ttm <- na.omit(simple_ttm)

#brighton_lsoa_to_school_times <- od2line(flow = simple_ttm, zones = lsoa_btn_pw_centroids, destinations = bh_sec_sch_bng, zone_code = "orig", dest_code = "dest", zone_code_d = "id")

#brighton_lsoa_to_school_times <- od2line(flow = simple_ttm, zones = lsoa_btn_pw_centroids, destinations = bh_sec_sch_bng, zone_code = "orig", dest_code = "dest", zone_code_d = "id")

#brighton_lsoa_to_school_times <- od2line(flow = simple_ttm, zones = lsoa_btn_pw_centroids, destinations = brighton_sec_schools)

#write_csv(simple_ttm, here("data", "simple_ttm.csv"))
#st_write(brighton_sec_schools, here("data", "brighton_sec_schools.geojson"), append = TRUE)

```
