---
title: "Reasonable Catchments"
author: "Professor Adam Dennett FRGS FAcSS, Professor of Urban Analytics, Bartlett Centre for Advanced Spatial Analysis, University College London - a.dennett@ucl.ac.uk - @adam_dennett"
published-title: 26/10/24
format: html
editor: visual
---

# Introduction

From the conversation in the community over the last few weeks, it's clear that one of the main objections to the council proposals relates to the fact that under some of the options presented, some students will be forced to travel very long distances to attend school.

To characterise the debate one side would point out the obsurdity of forcing large numbers of children to travel up to 5 miles to attend school - a journey that for some would take in excess of 1hr 30 mins on just a single leg or over 3 hrs of total travel time in a day.

The other side would then counter with - "well for some children already have to travel x miles or y minutes to access school, so why should they have to have this journey and others not?"

Both valid arguments. Given that neither of these situations is desirable - making more children travel more and some already having to do it - then it could be reasonably argued that under these circumstances, the utilitarian approach would be to try and minimise travel times for as many students as possible, while balancing that against maximising opportunities for giving more children access to good education.

Now, as is often the case, it's easy to claim some kind of moral superiority when these kind of debates get going - "I used to have to walk 1hr to school every day and it never did me any harm", "2hr bus journey? You should be so lucky - my kids were fortunate if they got home before 11pm and were up again at 5am and they all ended up at Cambridge University!" etc. - None of this is useful debate.

What might be useful is to look at that is usual or common. This will then give us some kind of baseline to compare other experiences to. What is the 'normal' distance travelled to Secondary school for children in England? For example. What is a common travel time for children living in cities? Because of course, we know that for those living in rural areas, long commutes to school might be normal.

And given that in a lot of places, the distance that a child might have to travel to school is governed by the catchment area they live in and correspondingly, the size of that catchment area, what might be considered a 'reasonable' catchment area?

## Reasonable Catchment Areas

The concept of a "reasonable" catchment area is actually enshrined in the legislation around School Admissions. The Department for Education (DfE) published the last iteration of the School Admissions Code in 2021 - <https://www.gov.uk/government/publications/school-admissions-code--2>

Within the PDF statutory guidance document that can be found on the main webpage - <https://assets.publishing.service.gov.uk/media/60ebfeb08fa8f50c76838685/School_admissions_code_2021.pdf> - there are some useful
