<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.280">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Professor Adam Dennett FRGS FAcSS, Professor of Urban Analytics, Bartlett Centre for Advanced Spatial Analysis, University College London - a.dennett@ucl.ac.uk">

<title>Brighton and Hove Secondary Schools Admission - Evidence Pages - Brighton and Hove Secondary School Admissions Proposal - Week 2 Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-HFKH18TWMG"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-HFKH18TWMG', { 'anonymize_ip': true});
</script>


<link rel="stylesheet" href="styles.css">
<meta property="og:title" content="Brighton and Hove Secondary Schools Admission - Evidence Pages - Brighton and Hove Secondary School Admissions Proposal - Week 2 Analysis">
<meta property="og:description" content="PAN - Published Admission Number. This is the number of pupils a school is permitted to allow to enter a school in Year 7.">
<meta property="og:site-name" content="Brighton and Hove Secondary Schools Admission - Evidence Pages">
<meta name="twitter:title" content="Brighton and Hove Secondary Schools Admission - Evidence Pages - Brighton and Hove Secondary School Admissions Proposal - Week 2 Analysis">
<meta name="twitter:description" content="PAN - Published Admission Number. This is the number of pupils a school is permitted to allow to enter a school in Year 7.">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Brighton and Hove Secondary Schools Admission - Evidence Pages</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./schools_wk2.html" aria-current="page">
 <span class="menu-text">Week 2 Analysis</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://adamdennett.co.uk"><i class="bi bi-person-circle" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/adam_dennett"><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-bi-github" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-bi-github">    
        <li>
    <a class="dropdown-item" href="https://github.com/adamdennett/BH_Secondary_Admissions_Analysis">
 <span class="dropdown-text">Source Code</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/adamdennett/BH_Secondary_Admissions_Analysis/issues">
 <span class="dropdown-text">Report a Bug</span></a>
  </li>  
    </ul>
  </li>
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#terminology" id="toc-terminology" class="nav-link active" data-scroll-target="#terminology">Terminology</a></li>
  <li><a href="#headlines-executive-summary" id="toc-headlines-executive-summary" class="nav-link" data-scroll-target="#headlines-executive-summary">Headlines / Executive Summary</a></li>
  <li><a href="#prelude---a-review-of-where-we-are-at-after-a-busy-week" id="toc-prelude---a-review-of-where-we-are-at-after-a-busy-week" class="nav-link" data-scroll-target="#prelude---a-review-of-where-we-are-at-after-a-busy-week">Prelude - a review of where we are at after a busy week</a>
  <ul class="collapse">
  <li><a href="#the-pan-problems" id="toc-the-pan-problems" class="nav-link" data-scroll-target="#the-pan-problems">The PAN Problem(s)</a>
  <ul class="collapse">
  <li><a href="#pan-background" id="toc-pan-background" class="nav-link" data-scroll-target="#pan-background">PAN Background</a></li>
  </ul></li>
  <li><a href="#pans-across-brighton" id="toc-pans-across-brighton" class="nav-link" data-scroll-target="#pans-across-brighton">PANS across Brighton</a></li>
  <li><a href="#pans-vs-applications-and-intake" id="toc-pans-vs-applications-and-intake" class="nav-link" data-scroll-target="#pans-vs-applications-and-intake">PANs vs Applications and Intake</a></li>
  <li><a href="#first-preferences-offers-and-rejections" id="toc-first-preferences-offers-and-rejections" class="nav-link" data-scroll-target="#first-preferences-offers-and-rejections">First Preferences, Offers and Rejections</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a></li>
  <li><a href="#proposed-changes-to-pans" id="toc-proposed-changes-to-pans" class="nav-link" data-scroll-target="#proposed-changes-to-pans">Proposed Changes to PANs</a>
  <ul class="collapse">
  <li><a href="#observations---council-proposed-pans" id="toc-observations---council-proposed-pans" class="nav-link" data-scroll-target="#observations---council-proposed-pans">Observations - Council Proposed PANs</a></li>
  <li><a href="#pan-2026-scenario-1---scaled-by-popularity" id="toc-pan-2026-scenario-1---scaled-by-popularity" class="nav-link" data-scroll-target="#pan-2026-scenario-1---scaled-by-popularity">PAN 2026 Scenario 1 - Scaled by Popularity</a></li>
  <li><a href="#pan-2026-scenario-2---scaled-by-even-reductions" id="toc-pan-2026-scenario-2---scaled-by-even-reductions" class="nav-link" data-scroll-target="#pan-2026-scenario-2---scaled-by-even-reductions">PAN 2026 Scenario 2 - Scaled by even reductions</a></li>
  <li><a href="#pan-2026-scenario-3---the-kings-scenario" id="toc-pan-2026-scenario-3---the-kings-scenario" class="nav-link" data-scroll-target="#pan-2026-scenario-3---the-kings-scenario">PAN 2026 Scenario 3 - the Kings Scenario</a></li>
  </ul></li>
  <li><a href="#closing-schools-in-brighton-and-hove-with-low-numbers" id="toc-closing-schools-in-brighton-and-hove-with-low-numbers" class="nav-link" data-scroll-target="#closing-schools-in-brighton-and-hove-with-low-numbers">Closing Schools in Brighton and Hove with low numbers</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/adamdennett/BH_Secondary_Admissions_Analysis/blob/main/schools_wk2.qmd" class="toc-action">View source</a></p><p><a href="https://github.com/adamdennett/BH_Secondary_Admissions_Analysis/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Brighton and Hove Secondary School Admissions Proposal - Week 2 Analysis</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Professor Adam Dennett FRGS FAcSS, Professor of Urban Analytics, Bartlett Centre for Advanced Spatial Analysis, University College London - a.dennett@ucl.ac.uk </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="terminology" class="level3">
<h3 class="anchored" data-anchor-id="terminology">Terminology</h3>
<p>PAN - Published Admission Number. This is the number of pupils a school is permitted to allow to enter a school in Year 7.</p>
<p>FSM - Free School Meals. This is the proportion of pupils in a school or residential area that receive free school meals because their household income is below a certain threshold. It is a widely used measure of social deprivation. In Brighton, the FSM threshold is currently household income below £16,190 - <a href="https://www.brighton-hove.gov.uk/schools-and-learning/free-school-meals" class="uri">https://www.brighton-hove.gov.uk/schools-and-learning/free-school-meals</a></p>
</section>
<section id="headlines-executive-summary" class="level1">
<h1>Headlines / Executive Summary</h1>
<ul>
<li><p><strong>PANs are one big driver of the issues. Despite what the Council says, from the analysis I have done, I believe there is no need to reduce PANs for most schools in the City in 2026 - reduction in PANS is necessary for some schools, but analysis below shows even for schools where they justifiably could be reduced, numbers still will be well in excess of their current admission figures and not smaller than the smallest school in the city.</strong></p></li>
<li><p><strong>Consequently, no change to current catchment boundaries is required in 2026 while still hitting Council PAN reduction targets.</strong></p></li>
<li><p>The desired increase in social mixing that the council is currently trialling through allowing FSM pupils from other catchments priority over students within, will in all likelihood lead to some of the outcomes already desired by the council (Social Mixing and achievement improvements). It is a pioneering initiative with potentially very positive outcomes that needs space and time to be fully evaluated. Results will not published until early 2025 - <em>after</em> any changes the council might try and push through under the current time table. In the People Overview and Scrutiny Committee held on 9/10/2024, the Council’s own expert, Dr Ellen Greaves, University of Exeter, urged the council to wait for the results of this initiative before making any changes to the admissions system. Artificially reducing PANS in high demand schools will amplify problems as out of catchment students attend popular schools.</p></li>
<li><p>PANS for Academies, Free Schools and Religious schools cannot currently be set by the council. However, in the above meeting, Councillor Haver* raised a point that a Government White Paper is on the horizon which may give local authorities the power to control ALL PANs in the near future - this could alleviate some of the issues I am about to describe still further.</p>
<p>*I think this was her name - audio wasn’t perfect</p></li>
<li><p>The argument that Cllr Taylor and Richard Barker made in the face-to-face meeting was that they would not consider a PAN lower than 180 for Longhill as it would make it unviable. This is demonstrably untrue when comparing similar schools across the country - and even within the City itself! The King’s Free school has a PAN of 165 and in a short time has become one of the most successful and thriving schools in the City. Analysis of all similar schools in England and Wales shows out of 1163 similar schools, Longhill ranks 496, with 495 smaller open 11-16 secondary schools in existence today.</p></li>
<li><p>In the work below, I offer a viable alternative to the proposals presented by the council. An equity driven scenario I have called the ‘Kings PAN Scenario’ which has the outcomes:</p>
<ul>
<li><p>no detrimental impact is felt across most schools in the city in 2026</p></li>
<li><p>a headline city-level PAN reduction is still achieved under the current council modelling scenarios</p></li>
<li><p>no school has PANs smaller than the smallest school already thriving in the city - and higher than or equal to their offers in 2024</p></li>
<li><p>options for the productive re-use of land (systems thinking) and should additional social and/or affordable housing be created on land released by reducing the estate, this could also contribute to the social mixing goals of the council in an otherwise relatively affluent area - a win win scenario.</p></li>
</ul></li>
</ul>
</section>
<section id="prelude---a-review-of-where-we-are-at-after-a-busy-week" class="level1">
<h1>Prelude - a review of where we are at after a busy week</h1>
<ul>
<li><p>After attending various in-person and online meetings, it has become clear that the Labour Council manifesto promise to ‘not close a school’ anywhere in the city, is a primary driving factor behind the proposals. As far as I am aware, there was nothing in the Labour Council manifesto that stated that it was their belief that the best way to achieve this was to artificially stuff low-demand schools on the geographic fringes of the city in areas of low child population, with children from more well-off parts of the city, against the wishes of them and their parents. This is the nub of the issue and why many people are very angry.</p></li>
<li><p>One of the schools at highest risk of closure - Longhill - is also, coincidentally, the school that Cllr Jacob Taylor (the Councillor leading the ) attended as a child, and a school that he had been a governor since 11 May 2021 until recently. He is no longer a governor there.</p></li>
<li><p>From what I have observed and listened to in these meetings, I am of the personal opinion that the educational mixing argument being promoted by the council as the main driver (alongside reducing roll numbers) for these proposals, while real, is actually secondary to the financial issues facing schools in the city. These are real and difficult to resolve and <a href="https://www.brightonandhovenews.org/2024/07/10/senior-councillor-airs-plans-to-federate-schools-to-tackle-deficits/">other solutions have been touted</a>. It is my personal opinion that giving FSM pupils better access to better performing schools in the city, while a brilliant goal and something that should be addressed, is also convenient cover promoting solutions that would only address the underlying financial challenges in an indirect way - my reason for believing this is the council have not even given their own pioneering FSM policy time to bear fruit. This is important, as if the council admitted financial challenges were the driver, then different ‘solutions’ to the problem (such as the one I suggest below) become viable.</p></li>
<li><p>There is a real issue of socio-economic deprivation and segregation in the city with residents in the most deprived Eastern parts of the city lacking both quality in education provision and choice. <a href="https://www.theguardian.com/education/2005/aug/09/schools.uk">This is a wider and long-term issue</a> and has driven initiatives to tackle socio-economic disadvantage through the school system and admissions shake-ups in the past, many of which have failed due to a lack of <a href="https://www.apm.org.uk/resources/find-a-resource/what-is-systems-thinking/">systems thinking</a>.</p></li>
<li><p>Compared to previous attempts to re-draw the catchments in Brighton, there is an additional challenge this time of reducing numbers of children in the city, reducing the money available from the government in a system which allocates money according to, primarily, pupil numbers and levels of deprivation associated with those pupils.</p></li>
<li><p>Brighton has what could be described as a ‘multiplier effect’ whereby the least popular provision is also geographically remote, but nearest to the most deprived children. A classic example of multiple deprivation.</p></li>
<li><p>The Council is faced with a big challenge, but rather than engaging in systems thinking and recognising that schools are a part of an interconnected urban ecosystem which encompasses the social fabric of the city with individual children, families and communities, transport systems, the environment, homes, jobs, and the economy, they are focusing only on the narrow educational dimensions of the problem, which while incredibly important, are no more or less important that the whole city system and cannot be managed in isolation from the rest of the city.</p></li>
<li><p>Having attended both the in-person consultation and the People Overview and Scrutiny Committee held on 9/10/2024, I still have the overwhelming impression that council is trying to rush through ill-conceived, poorly evidenced proposals that fail to look holistically at the problem. The level of objection from a huge number of families in the city is indicative of this failure.</p></li>
<li><p>A particularly big failure of process is that not only have the Council neglected the truly interconnected nature of schools and communities in the city, they have thus-far failed in their duty to carry out even the most basic evidence gathering and dissemination process before launching an engagement/consultation on the residents. Had they have completed this job in advance, they could have understood the problem better and come up with viable alternative, less disruptive, solutions - perhaps like the ones I propose below.</p></li>
<li><p>The Council have said that they will produce more evidence if this reaches the formal consultation stage, but it is my view that at this point it will be too late - to carry out the consultation properly, people need to be in possession of all of the facts. Evidence needs to come BEFORE policy. I am now even more of the strong opinion that the whole process needs to be paused to give time to build a comprehensive evidence base.</p></li>
<li><p>The council is giving the impression through its approach to this process that dogmatism and ideology are driving decisions more than full consideration of all relevant evidence - I sincerely hope my impressions in person are off the mark and I really do hope this is a mis-characterisation and I would love them to prove me wrong on this!</p></li>
<li><p>I have repeatedly asked the council to share their data with me and offered my services on multiple occasions to assist them in the evidence gathering I have expertise in. I have had some positive interations with Cllr Taylor and colleagues, but I am yet to receive any data. I have had correspondence that suggests it could be on the way, so I am keeping my fingers crossed.</p></li>
</ul>
<div class="cell">

</div>
<div class="cell">

</div>
<div class="cell">

</div>
<p>Much of the data presented on this page are taken from a rare example of published and useful data here - <a href="https://www.brighton-hove.gov.uk/allocation-factsheet-year-7-places-september-2024" class="uri">https://www.brighton-hove.gov.uk/allocation-factsheet-year-7-places-september-2024</a></p>
<p>PANS for 2026 and 2030 are derived from tables in the power point from the consultation website - <a href="https://yourvoice.brighton-hove.gov.uk/en-GB/projects/secondary-school-engagement-exercise/1" class="uri">https://yourvoice.brighton-hove.gov.uk/en-GB/projects/secondary-school-engagement-exercise/1</a></p>
<section id="the-pan-problems" class="level2">
<h2 class="anchored" data-anchor-id="the-pan-problems">The PAN Problem(s)</h2>
<section id="pan-background" class="level3">
<h3 class="anchored" data-anchor-id="pan-background">PAN Background</h3>
<p>It has become clearer to me over the last week that one of the big issues in this whole consultation process is the PAN - both the total PAN in different years (which relates to population projections produced by the Council), and the individual school-level PANs (which affect how many pupils a school can admit at year 7). I will explore both of these dimensions, but first some local background:</p>
<p>A school cannot legally admit fewer children than its PAN where pupils wish to attend the school. The PAN is determined (initially) by the physical size of the school by the Government’s <a href="https://www.gov.uk/guidance/net-capacity-assessment-nca-programme">Net Capacity Assessment Programme</a>, but it is not set in stone and can be reduced or increased according to demand. Physically larger schools may have artificially higher PANs even when lived pupil numbers are low.</p>
<ul>
<li><p>In most secondary schools in Brighton (Stringer, Varndean, Hove Park, Blatchington, Patcham, Longhill) the PAN is set by the council.</p></li>
<li><p>Religious and Free Schools such as Cardinal Newman and King’s School are allowed to set their own PANs and the council can’t (presently) intervene.</p></li>
<li><p>Academies (Brighton Aldridge Community Academy - BACA, and Portslade Aldridge Community Academy - PACA) are also allowed to set their own PANs and the council can’t intervene.</p></li>
</ul>
<p>One issue is that PANs for all schools contribute to the overall total number of ‘places’ in the City - but these don’t necessarily reflect pupils or their distribution (<a href="https://adamdennett.github.io/BH_Secondary_Admissions_Analysis/BH_Sec_Sch_Analysis.html">see my last paper if you want to know about geographic distribution</a>). So if the Council is determined to reduce the number of places (PANs) in the city, if the Religious Schools and the Academies refuse to reduce their PANs and the council is wedded to reducing numbers, the only way it can do this is by cutting, proportionally, MORE places from Stringer, Varndean, Hove Park, Blatchington, Patcham, Longhill than it would have done if it could control PANs everywhere. At least, that is the way they are operating at the moment - as we will see below, there are other options.</p>
<p>In the <a href="https://democracy.brighton-hove.gov.uk/ieListDocuments.aspx?CId=1129&amp;MId=11719&amp;Ver=4">People Overview and Scrutiny Committee held on 9/10/2024</a>, Councillor Haver* (*again, I think that was her name, not 100% sure) raised a point that a Government White Paper is on the horizon which may give local authorities the power to control ALL PANs in the near future - this could alleviate some of the issues I am about to describe, but at the moment, nothing can be done by the council to affect PANS in some schools in the city.</p>
</section>
</section>
<section id="pans-across-brighton" class="level2">
<h2 class="anchored" data-anchor-id="pans-across-brighton">PANS across Brighton</h2>
<p>The graph below in Figure 1 shows the PANs for 2024 taken from here:</p>
<p><a href="https://www.brighton-hove.gov.uk/allocation-factsheet-year-7-places-september-2024" class="uri">https://www.brighton-hove.gov.uk/allocation-factsheet-year-7-places-september-2024</a></p>
<div class="cell">
<div class="cell-output-display">
<p><img src="schools_wk2_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Figure 1 - PANs by School and Type, Brighton</em></p>
<p>We can see from this graph that the academy schools and King’s School have a relatively low PAN compared to other schools in the City, with Cardinal Newman enjoying a PAN well above average at 360. This represents 14% of the total places available.</p>
<p>As an interesting aside, we know from the 2021 Census that 30.9% of the population of Brighton identify as Christian - <a href="https://www.ons.gov.uk/census/maps/choropleth/identity/religion/religion-tb/christian?lad=E06000043" class="uri">https://www.ons.gov.uk/census/maps/choropleth/identity/religion/religion-tb/christian?lad=E06000043</a> - if we believe wikipedia - <a href="https://en.wikipedia.org/wiki/Religion_in_the_United_Kingdom" class="uri">https://en.wikipedia.org/wiki/Religion_in_the_United_Kingdom</a> - 13% of Christians in the UK are Catholic. So if we apply that percentage to Brighton, we can expect 3.9% of the population to be Roman Catholic. But 14% of the school places can be reserved for Catholic Children as a priority. I’ll just leave that there to sink in!</p>
</section>
<section id="pans-vs-applications-and-intake" class="level2">
<h2 class="anchored" data-anchor-id="pans-vs-applications-and-intake">PANs vs Applications and Intake</h2>
<p>The graph below in Figure 2 includes exactly the same numbers as above, but this time contextualises them relative to the total number of applications each school had in 2024 and the number of places that were actually offered to students that year.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="schools_wk2_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Figure 2 - PAN 2024 relative to counts of total applications and offers in the same year</em></p>
<p>A couple of things to point out:</p>
<ol type="1">
<li><p>Total Applications include all 1st, 2nd and 3rd choices for each school. It’s likely that schools in multi-school catchments may receive both first and second choices, potentially artificially inflating that number relative to the schools in single school catchments, so bear that in mind, however it can still be viewed as a crude measure of demand. I will disaggregate 1st, 2nd, and 3rd choices in some other graphs below.</p></li>
<li><p>All schools within multi-school catchments are very popular and are able to easily fill their offer numbers and probably could at least twice over - which is useful context when considering PAN reductions.</p></li>
<li><p>Some schools in Brighton received low numbers of applications. For BACA and Longhill, the numbers of applications they received were BELOW their PANs. These were not popular schools in 2024.</p></li>
<li><p>For BACA and Longhill, their total offer numbers were also below their PANs. This means the schools were very under-subscribed and had excess capacity. Longhill had a PAN of 270 and a total offer count of 94. Almost <strong><em>three times</em></strong> <strong><em>fewer</em></strong> students attending than there were places available.</p></li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="schools_wk2_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Figure 3 - Relative School Popularity (School 2024 Application to 2024 PAN ratio divided by Average 2024 Brighton Application to PAN ratio)</em></p>
<p>Another way of looking at Applications vs PANs is take the ratio of applications into PAN and compare this with the city average. In the graph in Figure 3 above, the data has been rescaled (code in the github link) so that anything &gt; 0 is greater popularity relative to other schools in the city, and anything &lt; 0 is less popular.</p>
<p>Interestingly, we can see that Kings School - the smallest in the city in terms of places available with a PAN of 165, is relatively the <em>most popular</em>, Longhill, on the other hand, is relatively the <em>least popular</em> even after scaling according to the city average.</p>
</section>
<section id="first-preferences-offers-and-rejections" class="level2">
<h2 class="anchored" data-anchor-id="first-preferences-offers-and-rejections">First Preferences, Offers and Rejections</h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="schools_wk2_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Figure 4 - PAN 2024 relative to total First Preference Applications, Offers and Rejections.</em></p>
<p>Some things to note here in Figure 4:</p>
<ol type="1">
<li><p>First Preferences and rejections are an alternative demand measure for a school and less affected by double counting than total applications. More rejections occur where first preferences are high.</p></li>
<li><p>Three schools - Varndean, King’s and Cardinal Newman had more first-preference than PANs, indicating very high demand.</p></li>
<li><p>BACA, PACA and Longhill have significantly more PANs than first preference and thus larger proportions of their cohorts are filled with students who did not choose them as a first choice, indicating low demand.</p></li>
</ol>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">Interpretation</h2>
<ul>
<li>We can see from the evidence above that <strong><em>PANS for schools in the city bear little or no relation to the popularity of the schools in 2024</em></strong>, as evidenced through their application figures. In fact, for the most popular schools, their first-preference applications are far in excess of the places they have been allocated by the council - their PANS could easily be much higher, relative to other schools in the City.</li>
<li>Some schools have PANs far in excess of their popularity which affects the rest of the system negatively. PANs matter when you have more demand than places as you can’t go any higher. When you have less demand than places in one school, the PAN is entirely irrelevant for the school (if you’ve only given out 94 offers, it doesn’t matter if your PAN is 270 or 2700!) but HUGELY relevant for the rest of the schools in the system as the number of pupils they can take in is reduced.</li>
</ul>
</section>
<section id="proposed-changes-to-pans" class="level2">
<h2 class="anchored" data-anchor-id="proposed-changes-to-pans">Proposed Changes to PANs</h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="schools_wk2_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><em>Figure 5 - 2024 PAN and Proposed 2026 and 2030 PANs under Option A of the Council’s reorganisation proposals.</em></p>
<p>*I should note that I have asked for the boundary data and numbers associated with the Option A boundary reorganisation, but at the time of writing have not received. These new boundaries are slightly different and will have slightly different pupil numbers within catchments, but they are similar enough to the present catchment to hopefully still be able to make reasonable comparison. If more and better data arrive in the future, I will of course re-visit and update.</p>
<ul>
<li><p>The graph above is a representation of the data provided in slide 11 of the <a href="https://yourvoice.brighton-hove.gov.uk/en-GB/projects/secondary-school-engagement-exercise/1">materials supplied by the council</a>. Under “Option A”, it’s clear to see that the council proposes to reduce PANS for all Council run schools in the city, first in 2026 and then again in 2030.</p></li>
<li><p>Below we see the same data, but this time in a table with the Council City-Wide PAN targets they have set at the bottom and three illustrative scenarios I have produced to explore the decisions the council is making and the biases in their PAN setting. The final column is a Scenario I am calling the “Kings 2026 PAN Scenario” which I will explain below.</p></li>
</ul>
<p><em>Table 1 - 2024 PAN and Various PAN scenarios</em></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped">
<caption>Council PAN and PAN Scenarios</caption>
<colgroup>
<col style="width: 24%">
<col style="width: 14%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 16%">
<col style="width: 13%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">School</th>
<th style="text-align: left;">Type</th>
<th style="text-align: right;">PAN 2024</th>
<th style="text-align: right;">PAN 2026</th>
<th style="text-align: right;">PAN 2030</th>
<th style="text-align: right;">PAN 2026 Scaled Popularity</th>
<th style="text-align: right;">PAN 2026 Scaled Even</th>
<th style="text-align: right;">PAN 2026 Kings Scenario</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Blatchington Mill School</td>
<td style="text-align: left;">Community school</td>
<td style="text-align: right;">330</td>
<td style="text-align: right;">300</td>
<td style="text-align: right;">240</td>
<td style="text-align: right;">289</td>
<td style="text-align: right;">315</td>
<td style="text-align: right;">330</td>
</tr>
<tr class="even">
<td style="text-align: left;">Brighton Aldridge Community Academy</td>
<td style="text-align: left;">Academy sponsor led</td>
<td style="text-align: right;">180</td>
<td style="text-align: right;">180</td>
<td style="text-align: right;">180</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">172</td>
<td style="text-align: right;">165</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cardinal Newman Catholic School</td>
<td style="text-align: left;">Voluntary aided school</td>
<td style="text-align: right;">360</td>
<td style="text-align: right;">360</td>
<td style="text-align: right;">360</td>
<td style="text-align: right;">388</td>
<td style="text-align: right;">343</td>
<td style="text-align: right;">360</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dorothy Stringer School</td>
<td style="text-align: left;">Community school</td>
<td style="text-align: right;">330</td>
<td style="text-align: right;">300</td>
<td style="text-align: right;">270</td>
<td style="text-align: right;">380</td>
<td style="text-align: right;">315</td>
<td style="text-align: right;">330</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hove Park School and Sixth Form Centre</td>
<td style="text-align: left;">Community school</td>
<td style="text-align: right;">180</td>
<td style="text-align: right;">180</td>
<td style="text-align: right;">180</td>
<td style="text-align: right;">250</td>
<td style="text-align: right;">172</td>
<td style="text-align: right;">180</td>
</tr>
<tr class="even">
<td style="text-align: left;">King’s School</td>
<td style="text-align: left;">Free schools</td>
<td style="text-align: right;">165</td>
<td style="text-align: right;">165</td>
<td style="text-align: right;">165</td>
<td style="text-align: right;">275</td>
<td style="text-align: right;">157</td>
<td style="text-align: right;">165</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Longhill High School</td>
<td style="text-align: left;">Community school</td>
<td style="text-align: right;">270</td>
<td style="text-align: right;">240</td>
<td style="text-align: right;">180</td>
<td style="text-align: right;">55</td>
<td style="text-align: right;">257</td>
<td style="text-align: right;">165</td>
</tr>
<tr class="even">
<td style="text-align: left;">Patcham High School</td>
<td style="text-align: left;">Community school</td>
<td style="text-align: right;">225</td>
<td style="text-align: right;">225</td>
<td style="text-align: right;">180</td>
<td style="text-align: right;">228</td>
<td style="text-align: right;">214</td>
<td style="text-align: right;">225</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Portslade Aldridge Community Academy</td>
<td style="text-align: left;">Academy sponsor led</td>
<td style="text-align: right;">220</td>
<td style="text-align: right;">220</td>
<td style="text-align: right;">220</td>
<td style="text-align: right;">128</td>
<td style="text-align: right;">210</td>
<td style="text-align: right;">220</td>
</tr>
<tr class="even">
<td style="text-align: left;">Varndean School</td>
<td style="text-align: left;">Community school</td>
<td style="text-align: right;">300</td>
<td style="text-align: right;">270</td>
<td style="text-align: right;">240</td>
<td style="text-align: right;">393</td>
<td style="text-align: right;">286</td>
<td style="text-align: right;">300</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Total</td>
<td style="text-align: right;">2560</td>
<td style="text-align: right;">2440</td>
<td style="text-align: right;">2215</td>
<td style="text-align: right;">2443</td>
<td style="text-align: right;">2441</td>
<td style="text-align: right;">2440</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="observations---council-proposed-pans" class="level3">
<h3 class="anchored" data-anchor-id="observations---council-proposed-pans">Observations - Council Proposed PANs</h3>
<ul>
<li>I have made a number of <a href="https://adamdennett.github.io/BH_Secondary_Admissions_Analysis/BH_Sec_Sch_Analysis.html#comparing-populations-of-2021-5-year-olds-with-available-school-places-in-2026.">earlier observations which look at proposed PAN reductions for different schools in the city</a> level relative to the population distribution of pupils and have shown that there are more severe reductions in areas of higher demand and less severe reductions in areas of lower demand, so I won’t go over that again here.</li>
<li>What I will comment on, however, are the PAN levels relative to school popularity - a related by slightly different dimension.</li>
</ul>
</section>
<section id="pan-2026-scenario-1---scaled-by-popularity" class="level3">
<h3 class="anchored" data-anchor-id="pan-2026-scenario-1---scaled-by-popularity">PAN 2026 Scenario 1 - Scaled by Popularity</h3>
<ul>
<li><p>Firstly, I should point out that these scenarios below are illustrative - I know that school entry numbers are predicated on multiples of 30, but these are designed to show the effect of different policies and priorities on these numbers.</p></li>
<li><p>Taking relative popularity as shown in Figure 3 above, and using that to scale up and down the PAN according the level of popularity in 2024, we see:</p>
<ul>
<li><p>The PANs for Dorothy Strings, Varndean, Hove Park, Kings, and Varndean in 2026 would all increase by quite large numbers of pupils, reflecting their popularity and accommodating demand.</p></li>
<li><p>The PANs for Blatchington Mill would reduce almost in line with proposals, Cardinal newman, already with a high PAN, would remain similar, and Patcham would remain virtually the same.</p></li>
<li><p>The PANs for BACA, PACA and Longhill would decline considerably and to the point where they would not be viable schools.</p></li>
</ul></li>
<li><p>As stated at the top, this is merely illustrative and NOT in any form a recommendation, but it is useful to explore how the reality of school popularity would change the PANs across the city if it were used.</p></li>
</ul>
</section>
<section id="pan-2026-scenario-2---scaled-by-even-reductions" class="level3">
<h3 class="anchored" data-anchor-id="pan-2026-scenario-2---scaled-by-even-reductions">PAN 2026 Scenario 2 - Scaled by even reductions</h3>
<ul>
<li><p>What would happen if the council reduced PANs down for each school, but did so evenly across the whole city, according to their current distributions? i.e.&nbsp;dividing each school PAN 2004 by the total Brighton PAN in 2024 and simply multiplying that proportion by the 2026 Brighton Total PAN. Again, I know these don’t fit into multiples of 30, but help for illustration.</p></li>
<li><p>What this scenario is useful for is exploring is the impact of some schools being able to opt out of reducing thir PANs. If all things were equal, the 2026 Scaled Even PAN would be the same as the Council 2026 PAN.</p></li>
<li><p>As we can see, things are not equal. Part of this, of course, it due to the fact mentioned earlier that BACA, PACA, Cardinal Newman and Kings set their own PANs at the moment and the Council can’t change this.</p></li>
<li><p>However, we can start to see which schools are hit harder by the intractability of not being able to make the non-council run schools take their fair share of the hit.</p>
<ul>
<li><p>Blatchington Mill’s PAN is 15 pupils lower than expected</p></li>
<li><p>Longhill is 17 students lower than expected</p></li>
<li><p>Dorothy Stringer 15 students lower</p></li>
<li><p>Varndean at 15/16 students lower.</p></li>
</ul></li>
<li><p>The presence of schools in the system that can set their own PANs, unfairly disadvantages other schools who can’t in this scenario.</p></li>
<li><p>We can see that more-or-less what the council are proposing - factoring out the schools they can’t control - is something close to this equal reduction scenario, with Patcham perhaps being a little more equal than the others. However, equality is quite different from <em>equity</em>, which pays attention to different levels of need.</p></li>
</ul>
</section>
<section id="pan-2026-scenario-3---the-kings-scenario" class="level3">
<h3 class="anchored" data-anchor-id="pan-2026-scenario-3---the-kings-scenario">PAN 2026 Scenario 3 - the Kings Scenario</h3>
<ul>
<li><p>This scenario takes a little explaining which I will do below. One way of thinking about this scenario is it is the <strong><em>EQUITY</em></strong> scenario. It pays more attention to equality but also pays some attention to need as defined by demand for places. It is designed to offer an alternative to focusing just on popularity or equality. The outcomes of this scenario are:</p>
<ul>
<li><p>Most schools in the city don’t need to alter their 2026 PANs from current levels at all.</p></li>
<li><p>No school in the City has a PAN lower than the demonstrably viable 165 PAN that Kings School already has (hence the scenario name).</p></li>
<li><p>PANs are more closely aligned with demand, although a number of schools are ‘donating to the system’ - doing their bit for the good of the whole school system in the city by having PANs considerably lower than their demand levels would suggest, allowing less popular schools to retain viability.</p></li>
</ul></li>
</ul>
<p>Below, some more context to this problem:</p>
<section id="small-school-viability---the-baca-and-longhill-challenge" class="level4">
<h4 class="anchored" data-anchor-id="small-school-viability---the-baca-and-longhill-challenge">Small School Viability - the BACA and Longhill challenge</h4>
<p>In the Town Hall face-to-face meeting on Tuesday, Cllr Taylor stated two relevant things:</p>
<p>1) The Labour Council campaigned on a manifesto that promised that it would not close a school within Brighton and Hove.</p>
<p>2) That it was his view that a year 7 PAN of lower than 180 would not be possible for a viable school that could remain open.</p>
<p>The latter is tied intrinsically to the former with these two statements, but is this really the case? Let’s unpick this a little and zoom in on the second of the statements.</p>
</section>
<section id="small-schools-in-england-and-wales" class="level4">
<h4 class="anchored" data-anchor-id="small-schools-in-england-and-wales">Small Schools in England and Wales</h4>
<p>The Government provides data on all schools in England and Wales through their edubase dataset, published annually. <a href="https://get-information-schools.service.gov.uk/" class="uri">https://get-information-schools.service.gov.uk/</a></p>
<p>In order that we are comparing like-with-like, let’s only look at state-funded 11-16 schools in England and Wales. The histogram below shows the distribution of the number of pupils in these schools. The red and cyan lines show the number of pupils at Longhill and PACA respectively.</p>
<p>I have not included BACA in this graph as it is an 11-19 school and thus not directly comparable, however the recorded number on its role in 2024 is 802 - so a much smaller school than Longhill.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="schools_wk2_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="closing-schools-in-brighton-and-hove-with-low-numbers" class="level2">
<h2 class="anchored" data-anchor-id="closing-schools-in-brighton-and-hove-with-low-numbers">Closing Schools in Brighton and Hove with low numbers</h2>
<p>The council has repeated cited at the in person consultation meeting I attended and again in the <a href="https://democracy.brighton-hove.gov.uk/ieListDocuments.aspx?CId=1129&amp;MId=11719&amp;Ver=4">People Overview and Scrutiny Committee held on 9/10/2024</a> that it is not sustainable to have schools with low numbers of pupils. In the Scrutiny meeting, Councillor Haver asked a question about the minimum viability of schools.</p>
<p>Councillor Collier and Colleague commented that is was their view that 180 pupils was the <em>minimum</em> single year PAN they would consider viable.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="schools_wk2_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#get some LSOA pop weighted centroids for E&amp;W from ONS</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/LLSOA_Dec_2021_PWC_for_England_and_Wales_2022/FeatureServer/0/query?outFields=*&amp;where=1%3D1&amp;f=geojson"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read the GeoJSON file into an sf object</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>sf_point_data <span class="ot">&lt;-</span> <span class="fu">st_read</span>(url)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `OGRGeoJSON' from data source 
  `https://services1.arcgis.com/ESMARspQHYMw9BZ9/arcgis/rest/services/LLSOA_Dec_2021_PWC_for_England_and_Wales_2022/FeatureServer/0/query?outFields=*&amp;where=1%3D1&amp;f=geojson' 
  using driver `GeoJSON'
Simple feature collection with 35672 features and 3 fields
Geometry type: POINT
Dimension:     XY
Bounding box:  xmin: -6.311076 ymin: 49.916 xmax: 1.754594 ymax: 55.78286
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#save locally</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">st_write</span>(sf_point_data, <span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"EW_LSOA_PW_Centoid.geojson"</span>), <span class="at">append =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Updating layer `EW_LSOA_PW_Centoid' to data source `E:/BH_Schools_2/data/EW_LSOA_PW_Centoid.geojson' using driver `GeoJSON'
Updating existing layer EW_LSOA_PW_Centoid
Writing 35672 features with 3 fields and geometry type Point.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#brighton school data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>brighton_school_children <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"BrightonLSOASchoolChildren.csv"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Rows: 165 Columns: 17
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (2): lsoa_name, lsoa_code
dbl (15): total_people, total_pct, total_bh_prop, 5_9_total, 5_9_lsoa_pct, 5...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>btn_lsoa_list <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(brighton_school_children<span class="sc">$</span>lsoa_code) <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">clean_names</span>()</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>lsoa_btn_pw_centroids <span class="ot">&lt;-</span> sf_point_data <span class="sc">%&gt;%</span> </span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="dv">27700</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  clean_names <span class="sc">%&gt;%</span> </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(lsoa21cd, geometry)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>lsoa_btn_pw_centroids <span class="ot">&lt;-</span> lsoa_btn_pw_centroids <span class="sc">%&gt;%</span> <span class="fu">right_join</span>(btn_lsoa_list, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"lsoa21cd"</span> <span class="ot">=</span> <span class="st">"brighton_school_children_lsoa_code"</span>))</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="fu">st_write</span>(lsoa_btn_pw_centroids, <span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"lsoa_btn_pw_centroids.geojson"</span>), <span class="at">append =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Updating layer `lsoa_btn_pw_centroids' to data source `E:/BH_Schools_2/data/lsoa_btn_pw_centroids.geojson' using driver `GeoJSON'
Updating existing layer lsoa_btn_pw_centroids
Writing 165 features with 1 fields and geometry type Point.</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `BrightonSecondaryCatchments' from data source 
  `E:\BH_Schools_2\data\BrightonSecondaryCatchments.geojson' 
  using driver `GeoJSON'
Simple feature collection with 6 features and 2 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 523887.8 ymin: 100896.4 xmax: 539613.4 ymax: 110190.1
Projected CRS: OSGB36 / British National Grid</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `EW_LSOA' from data source `E:\BH_Schools_2\data\EW_LSOA.geojson' using driver `GeoJSON'
Simple feature collection with 35672 features and 11 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: -6.418667 ymin: 49.86467 xmax: 1.763706 ymax: 55.81109
Geodetic CRS:  WGS 84</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `oa_brighton' from data source 
  `E:\BH_Schools_2\data\oa_brighton.geojson' using driver `GeoJSON'
Simple feature collection with 936 features and 10 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 523598.1 ymin: 101780.1 xmax: 539862.4 ymax: 111919.1
Projected CRS: OSGB36 / British National Grid</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `brighton_roads' from data source 
  `E:\BH_Schools_2\data\brighton_roads.shp' using driver `ESRI Shapefile'
Simple feature collection with 4746 features and 9 fields
Geometry type: MULTILINESTRING
Dimension:     XY
Bounding box:  xmin: 523824.1 ymin: 101686.4 xmax: 539547.8 ymax: 112419.1
Projected CRS: OSGB36 / British National Grid</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "21"</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#travel time matrix</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Set parameters</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>mode <span class="ot">=</span> <span class="fu">c</span>(<span class="st">"WALK"</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>max_walk_time <span class="ot">=</span> <span class="dv">90</span> <span class="co"># minutes</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>max_trip_duration <span class="ot">=</span> <span class="dv">90</span> <span class="co"># minutes</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>departure_datetime <span class="ot">=</span> <span class="fu">as.POSIXct</span>(<span class="st">"23-05-2024 8:30:00"</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>                                 <span class="at">format =</span> <span class="st">"%d-%m-%Y %H:%M:%S"</span>, </span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>                                <span class="at">tz =</span> <span class="st">"GMT"</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="co">#note the code below already requires the h3 core matrix to be set up</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the travel time matrix by Transit</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>ttm_btn_lsoa_to_School <span class="ot">=</span> <span class="fu">travel_time_matrix</span>(<span class="at">r5r_core =</span> r5r_core,</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>                          <span class="at">origins =</span> bh_sec_sch,</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>                          <span class="at">destinations =</span> brighton_lsoa_points_r5,</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>                          <span class="at">mode =</span> mode,</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>                          <span class="at">departure_datetime =</span> departure_datetime,</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>                          <span class="at">max_walk_time =</span> max_walk_time,</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>                          <span class="at">max_trip_duration =</span> max_trip_duration)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in assign_points_input(origins, "origins"): 'origins$id' forcefully
cast to character.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in assign_points_input(destinations, "destinations"): 'destinations$id'
forcefully cast to character.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#join codes back to the matrix and get it ready from plotting</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>ttm_btn_lsoa_to_School<span class="sc">$</span>orig_lsoa <span class="ot">&lt;-</span> brighton_lsoa_centroids<span class="sc">$</span>lsoa21cd[<span class="fu">match</span>(ttm_btn_lsoa_to_School<span class="sc">$</span>to_id, brighton_lsoa_centroids<span class="sc">$</span>fid)]</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>ttm_btn_lsoa_to_School<span class="sc">$</span>dest_sch <span class="ot">&lt;-</span> brighton_sec_schools_wgs84<span class="sc">$</span>establishment_name[<span class="fu">match</span>(ttm_btn_lsoa_to_School<span class="sc">$</span>from_id, brighton_sec_schools_wgs84<span class="sc">$</span>urn)]</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>ttm_btn_lsoa_to_School <span class="ot">&lt;-</span> ttm_btn_lsoa_to_School <span class="sc">%&gt;%</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">to_id =</span> <span class="fu">as.factor</span>(to_id)) <span class="sc">%&gt;%</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unite</span>(od_code, orig_lsoa, to_id, <span class="at">sep =</span> <span class="st">"_"</span>, <span class="at">remove =</span> <span class="cn">FALSE</span>)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>simple_ttm <span class="ot">&lt;-</span> ttm_btn_lsoa_to_School <span class="sc">%&gt;%</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(orig_lsoa, to_id, travel_time_p50) <span class="sc">%&gt;%</span> </span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">orig =</span> orig_lsoa, <span class="at">dest =</span> to_id, <span class="at">flow =</span> travel_time_p50)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(ttm_btn_lsoa_to_School)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>simple_ttm <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(simple_ttm)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co">#brighton_lsoa_to_school_times &lt;- od2line(flow = simple_ttm, zones = lsoa_btn_pw_centroids, destinations = bh_sec_sch_bng, zone_code = "orig", dest_code = "dest", zone_code_d = "id")</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co">#brighton_lsoa_to_school_times &lt;- od2line(flow = simple_ttm, zones = lsoa_btn_pw_centroids, destinations = bh_sec_sch_bng, zone_code = "orig", dest_code = "dest", zone_code_d = "id")</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co">#brighton_lsoa_to_school_times &lt;- od2line(flow = simple_ttm, zones = lsoa_btn_pw_centroids, destinations = brighton_sec_schools)</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co">#write_csv(simple_ttm, here("data", "simple_ttm.csv"))</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="co">#st_write(brighton_sec_schools, here("data", "brighton_sec_schools.geojson"), append = TRUE)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Remember VAT on private schools - look at private school numbers in the city</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>